services:
  service-front:
    image: node:22
    ports: [3000:3000]
    working_dir: /app
    environment:
      - NUXT_PUBLIC_STRIPE_KEY=${STRIPE_KEY}
      - NUXT_PUBLIC_STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./service-front/src:/app